// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.18.1
// source: niuniu.proto

package niuniu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 牌型类型
type BullType int32

const (
	BullType_NO_POINT   BullType = 0  // 无点牌
	BullType_ONE        BullType = 1  // 牛一
	BullType_TWO        BullType = 2  // 牛二
	BullType_THREE      BullType = 3  // 牛三
	BullType_FOUR       BullType = 4  // 牛四
	BullType_FIVE       BullType = 5  // 牛五
	BullType_SIX        BullType = 6  // 牛六
	BullType_SEVEN      BullType = 7  // 牛七
	BullType_EIGHT      BullType = 8  // 牛八
	BullType_NINE       BullType = 9  // 牛九
	BullType_BULL       BullType = 10 // 牛牛
	BullType_FOURBOMB   BullType = 11 // 四炸
	BullType_FIVEFLOWER BullType = 12 // 五花
	BullType_FIVESMALL  BullType = 13 // 五小
)

// Enum value maps for BullType.
var (
	BullType_name = map[int32]string{
		0:  "NO_POINT",
		1:  "ONE",
		2:  "TWO",
		3:  "THREE",
		4:  "FOUR",
		5:  "FIVE",
		6:  "SIX",
		7:  "SEVEN",
		8:  "EIGHT",
		9:  "NINE",
		10: "BULL",
		11: "FOURBOMB",
		12: "FIVEFLOWER",
		13: "FIVESMALL",
	}
	BullType_value = map[string]int32{
		"NO_POINT":   0,
		"ONE":        1,
		"TWO":        2,
		"THREE":      3,
		"FOUR":       4,
		"FIVE":       5,
		"SIX":        6,
		"SEVEN":      7,
		"EIGHT":      8,
		"NINE":       9,
		"BULL":       10,
		"FOURBOMB":   11,
		"FIVEFLOWER": 12,
		"FIVESMALL":  13,
	}
)

func (x BullType) Enum() *BullType {
	p := new(BullType)
	*p = x
	return p
}

func (x BullType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BullType) Descriptor() protoreflect.EnumDescriptor {
	return file_niuniu_proto_enumTypes[0].Descriptor()
}

func (BullType) Type() protoreflect.EnumType {
	return &file_niuniu_proto_enumTypes[0]
}

func (x BullType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BullType.Descriptor instead.
func (BullType) EnumDescriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{0}
}

type GameStatus int32

const (
	GameStatus_IDLE          GameStatus = 0 // 空闲,等待玩家准备
	GameStatus_COUNTDOWN     GameStatus = 1 // 开始倒计时
	GameStatus_BEGIN         GameStatus = 2 // 开始
	GameStatus_BANKER        GameStatus = 3 // 抢庄
	GameStatus_BANKER_NOTIFY GameStatus = 4 // 通知庄
	GameStatus_BET           GameStatus = 5 // 下注
	GameStatus_DEAL_CARDS    GameStatus = 6 // 发牌
	GameStatus_SHOW_CARDS    GameStatus = 7 // 亮牌
	GameStatus_TALLY         GameStatus = 8 // 游戏结算
	GameStatus_OVER          GameStatus = 9 // 游戏结束
)

// Enum value maps for GameStatus.
var (
	GameStatus_name = map[int32]string{
		0: "IDLE",
		1: "COUNTDOWN",
		2: "BEGIN",
		3: "BANKER",
		4: "BANKER_NOTIFY",
		5: "BET",
		6: "DEAL_CARDS",
		7: "SHOW_CARDS",
		8: "TALLY",
		9: "OVER",
	}
	GameStatus_value = map[string]int32{
		"IDLE":          0,
		"COUNTDOWN":     1,
		"BEGIN":         2,
		"BANKER":        3,
		"BANKER_NOTIFY": 4,
		"BET":           5,
		"DEAL_CARDS":    6,
		"SHOW_CARDS":    7,
		"TALLY":         8,
		"OVER":          9,
	}
)

func (x GameStatus) Enum() *GameStatus {
	p := new(GameStatus)
	*p = x
	return p
}

func (x GameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_niuniu_proto_enumTypes[1].Descriptor()
}

func (GameStatus) Type() protoreflect.EnumType {
	return &file_niuniu_proto_enumTypes[1]
}

func (x GameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStatus.Descriptor instead.
func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{1}
}

type OutCardInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  BullType `protobuf:"varint,1,opt,name=type,proto3,enum=logic.niuniu.BullType" json:"type,omitempty"`
	Cards []byte   `protobuf:"bytes,2,opt,name=cards,proto3" json:"cards,omitempty"` // 有牛: 前三张为组成牛牛的三张牌, 其它从大到小排序
}

func (x *OutCardInfo) Reset() {
	*x = OutCardInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutCardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutCardInfo) ProtoMessage() {}

func (x *OutCardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutCardInfo.ProtoReflect.Descriptor instead.
func (*OutCardInfo) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{0}
}

func (x *OutCardInfo) GetType() BullType {
	if x != nil {
		return x.Type
	}
	return BullType_NO_POINT
}

func (x *OutCardInfo) GetCards() []byte {
	if x != nil {
		return x.Cards
	}
	return nil
}

type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId    uint32       `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Status    GameStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=logic.niuniu.GameStatus" json:"status,omitempty"`
	Ready     int32        `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	BankerRob int32        `protobuf:"varint,4,opt,name=banker_rob,json=bankerRob,proto3" json:"banker_rob,omitempty"` // 抢庄
	IsBanker  bool         `protobuf:"varint,5,opt,name=is_banker,json=isBanker,proto3" json:"is_banker,omitempty"`
	BetRate   int32        `protobuf:"varint,6,opt,name=bet_rate,json=betRate,proto3" json:"bet_rate,omitempty"`      // 下注倍率
	HandCards []byte       `protobuf:"bytes,7,opt,name=hand_cards,json=handCards,proto3" json:"hand_cards,omitempty"` //
	OutCard   *OutCardInfo `protobuf:"bytes,8,opt,name=out_card,json=outCard,proto3" json:"out_card,omitempty"`
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInfo) GetSeatId() uint32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *PlayerInfo) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_IDLE
}

func (x *PlayerInfo) GetReady() int32 {
	if x != nil {
		return x.Ready
	}
	return 0
}

func (x *PlayerInfo) GetBankerRob() int32 {
	if x != nil {
		return x.BankerRob
	}
	return 0
}

func (x *PlayerInfo) GetIsBanker() bool {
	if x != nil {
		return x.IsBanker
	}
	return false
}

func (x *PlayerInfo) GetBetRate() int32 {
	if x != nil {
		return x.BetRate
	}
	return 0
}

func (x *PlayerInfo) GetHandCards() []byte {
	if x != nil {
		return x.HandCards
	}
	return nil
}

func (x *PlayerInfo) GetOutCard() *OutCardInfo {
	if x != nil {
		return x.OutCard
	}
	return nil
}

type GameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status GameStatus `protobuf:"varint,4,opt,name=status,proto3,enum=logic.niuniu.GameStatus" json:"status,omitempty"` // 游戏状态
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{2}
}

func (x *GameInfo) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_IDLE
}

// 游戏全量信息
type GameInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameInfoRequest) Reset() {
	*x = GameInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfoRequest) ProtoMessage() {}

func (x *GameInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfoRequest.ProtoReflect.Descriptor instead.
func (*GameInfoRequest) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{3}
}

type GameInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameConf   string        `protobuf:"bytes,1,opt,name=game_conf,json=gameConf,proto3" json:"game_conf,omitempty"`
	GameInfo   *GameInfo     `protobuf:"bytes,2,opt,name=game_info,json=gameInfo,proto3" json:"game_info,omitempty"`
	PlayerInfo []*PlayerInfo `protobuf:"bytes,3,rep,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
}

func (x *GameInfoResponse) Reset() {
	*x = GameInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfoResponse) ProtoMessage() {}

func (x *GameInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfoResponse.ProtoReflect.Descriptor instead.
func (*GameInfoResponse) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{4}
}

func (x *GameInfoResponse) GetGameConf() string {
	if x != nil {
		return x.GameConf
	}
	return ""
}

func (x *GameInfoResponse) GetGameInfo() *GameInfo {
	if x != nil {
		return x.GameInfo
	}
	return nil
}

func (x *GameInfoResponse) GetPlayerInfo() []*PlayerInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

type NotifyGameStatusChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeforeStatus GameStatus `protobuf:"varint,1,opt,name=before_status,json=beforeStatus,proto3,enum=logic.niuniu.GameStatus" json:"before_status,omitempty"` // 游戏状态
	CurrStatus   GameStatus `protobuf:"varint,2,opt,name=curr_status,json=currStatus,proto3,enum=logic.niuniu.GameStatus" json:"curr_status,omitempty"`
	StatusAt     uint32     `protobuf:"varint,3,opt,name=status_at,json=statusAt,proto3" json:"status_at,omitempty"`    // 状态开始时间戳
	CountDown    int32      `protobuf:"varint,4,opt,name=count_down,json=countDown,proto3" json:"count_down,omitempty"` // 倒计时
}

func (x *NotifyGameStatusChange) Reset() {
	*x = NotifyGameStatusChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyGameStatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyGameStatusChange) ProtoMessage() {}

func (x *NotifyGameStatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyGameStatusChange.ProtoReflect.Descriptor instead.
func (*NotifyGameStatusChange) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{5}
}

func (x *NotifyGameStatusChange) GetBeforeStatus() GameStatus {
	if x != nil {
		return x.BeforeStatus
	}
	return GameStatus_IDLE
}

func (x *NotifyGameStatusChange) GetCurrStatus() GameStatus {
	if x != nil {
		return x.CurrStatus
	}
	return GameStatus_IDLE
}

func (x *NotifyGameStatusChange) GetStatusAt() uint32 {
	if x != nil {
		return x.StatusAt
	}
	return 0
}

func (x *NotifyGameStatusChange) GetCountDown() int32 {
	if x != nil {
		return x.CountDown
	}
	return 0
}

// 用户请求抢庄
type PlayerRobBankerReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rob int32 `protobuf:"varint,2,opt,name=rob,proto3" json:"rob,omitempty"` // 1:不抢, 2: 抢
}

func (x *PlayerRobBankerReport) Reset() {
	*x = PlayerRobBankerReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerRobBankerReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRobBankerReport) ProtoMessage() {}

func (x *PlayerRobBankerReport) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRobBankerReport.ProtoReflect.Descriptor instead.
func (*PlayerRobBankerReport) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerRobBankerReport) GetRob() int32 {
	if x != nil {
		return x.Rob
	}
	return 0
}

// 广播抢庄用户
type NotifyPlayerRobBanker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId uint32 `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Rob    int32  `protobuf:"varint,2,opt,name=rob,proto3" json:"rob,omitempty"`
}

func (x *NotifyPlayerRobBanker) Reset() {
	*x = NotifyPlayerRobBanker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyPlayerRobBanker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPlayerRobBanker) ProtoMessage() {}

func (x *NotifyPlayerRobBanker) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPlayerRobBanker.ProtoReflect.Descriptor instead.
func (*NotifyPlayerRobBanker) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{7}
}

func (x *NotifyPlayerRobBanker) GetSeatId() uint32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *NotifyPlayerRobBanker) GetRob() int32 {
	if x != nil {
		return x.Rob
	}
	return 0
}

// 广播庄家位置
type NotifyBankerSeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId uint32 `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
}

func (x *NotifyBankerSeat) Reset() {
	*x = NotifyBankerSeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyBankerSeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBankerSeat) ProtoMessage() {}

func (x *NotifyBankerSeat) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBankerSeat.ProtoReflect.Descriptor instead.
func (*NotifyBankerSeat) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{8}
}

func (x *NotifyBankerSeat) GetSeatId() uint32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

// 闲家下注
type PlayerBetRateReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rate int32 `protobuf:"varint,1,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *PlayerBetRateReport) Reset() {
	*x = PlayerBetRateReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerBetRateReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBetRateReport) ProtoMessage() {}

func (x *PlayerBetRateReport) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBetRateReport.ProtoReflect.Descriptor instead.
func (*PlayerBetRateReport) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerBetRateReport) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

// 广播闲家下注倍率信息
type NotifyPlayerBetRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId uint32 `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Rate   int32  `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
}

func (x *NotifyPlayerBetRate) Reset() {
	*x = NotifyPlayerBetRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyPlayerBetRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPlayerBetRate) ProtoMessage() {}

func (x *NotifyPlayerBetRate) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPlayerBetRate.ProtoReflect.Descriptor instead.
func (*NotifyPlayerBetRate) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{10}
}

func (x *NotifyPlayerBetRate) GetSeatId() uint32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *NotifyPlayerBetRate) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

// 通知用户手牌信息
type NotifyPlayerHandCards struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId    uint32 `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	HandCards []byte `protobuf:"bytes,2,opt,name=hand_cards,json=handCards,proto3" json:"hand_cards,omitempty"`
}

func (x *NotifyPlayerHandCards) Reset() {
	*x = NotifyPlayerHandCards{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyPlayerHandCards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPlayerHandCards) ProtoMessage() {}

func (x *NotifyPlayerHandCards) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPlayerHandCards.ProtoReflect.Descriptor instead.
func (*NotifyPlayerHandCards) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{11}
}

func (x *NotifyPlayerHandCards) GetSeatId() uint32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *NotifyPlayerHandCards) GetHandCards() []byte {
	if x != nil {
		return x.HandCards
	}
	return nil
}

// 请求上传出牌信息
type PlayerOutCardReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutCard *OutCardInfo `protobuf:"bytes,1,opt,name=out_card,json=outCard,proto3" json:"out_card,omitempty"`
}

func (x *PlayerOutCardReport) Reset() {
	*x = PlayerOutCardReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerOutCardReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOutCardReport) ProtoMessage() {}

func (x *PlayerOutCardReport) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOutCardReport.ProtoReflect.Descriptor instead.
func (*PlayerOutCardReport) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerOutCardReport) GetOutCard() *OutCardInfo {
	if x != nil {
		return x.OutCard
	}
	return nil
}

// 广播用户出牌结果
type NotifyPlayerOutCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId  uint32       `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	OutCard *OutCardInfo `protobuf:"bytes,2,opt,name=out_card,json=outCard,proto3" json:"out_card,omitempty"`
}

func (x *NotifyPlayerOutCard) Reset() {
	*x = NotifyPlayerOutCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyPlayerOutCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPlayerOutCard) ProtoMessage() {}

func (x *NotifyPlayerOutCard) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPlayerOutCard.ProtoReflect.Descriptor instead.
func (*NotifyPlayerOutCard) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{13}
}

func (x *NotifyPlayerOutCard) GetSeatId() uint32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *NotifyPlayerOutCard) GetOutCard() *OutCardInfo {
	if x != nil {
		return x.OutCard
	}
	return nil
}

// 游戏结算
type NotifyGameTally struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TallInfo []*NotifyGameTally_TallyInfo `protobuf:"bytes,2,rep,name=tall_info,json=tallInfo,proto3" json:"tall_info,omitempty"` // 用户输户赢信息
}

func (x *NotifyGameTally) Reset() {
	*x = NotifyGameTally{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyGameTally) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyGameTally) ProtoMessage() {}

func (x *NotifyGameTally) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyGameTally.ProtoReflect.Descriptor instead.
func (*NotifyGameTally) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{14}
}

func (x *NotifyGameTally) GetTallInfo() []*NotifyGameTally_TallyInfo {
	if x != nil {
		return x.TallInfo
	}
	return nil
}

type NotifyGameTally_TallyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId uint32 `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Coins  int32  `protobuf:"varint,2,opt,name=coins,proto3" json:"coins,omitempty"`
}

func (x *NotifyGameTally_TallyInfo) Reset() {
	*x = NotifyGameTally_TallyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_niuniu_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyGameTally_TallyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyGameTally_TallyInfo) ProtoMessage() {}

func (x *NotifyGameTally_TallyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_niuniu_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyGameTally_TallyInfo.ProtoReflect.Descriptor instead.
func (*NotifyGameTally_TallyInfo) Descriptor() ([]byte, []int) {
	return file_niuniu_proto_rawDescGZIP(), []int{14, 0}
}

func (x *NotifyGameTally_TallyInfo) GetSeatId() uint32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *NotifyGameTally_TallyInfo) GetCoins() int32 {
	if x != nil {
		return x.Coins
	}
	return 0
}

var File_niuniu_proto protoreflect.FileDescriptor

var file_niuniu_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x22, 0x4f, 0x0a, 0x0b,
	0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x2e, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x2e, 0x42, 0x75, 0x6c, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x63, 0x61, 0x72, 0x64, 0x73, 0x22, 0x99, 0x02,
	0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07,
	0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73,
	0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x6e, 0x69,
	0x75, 0x6e, 0x69, 0x75, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x62, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x5f, 0x72, 0x6f, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x62, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x52, 0x6f, 0x62, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x73, 0x5f, 0x62, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x42, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x65, 0x74,
	0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x65, 0x74,
	0x52, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x5f, 0x63, 0x61, 0x72,
	0x64, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x43, 0x61,
	0x72, 0x64, 0x73, 0x12, 0x34, 0x0a, 0x08, 0x6f, 0x75, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x6e, 0x69,
	0x75, 0x6e, 0x69, 0x75, 0x2e, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x07, 0x6f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x22, 0x3c, 0x0a, 0x08, 0x47, 0x61, 0x6d,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x6e, 0x69,
	0x75, 0x6e, 0x69, 0x75, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x9f, 0x01, 0x0a, 0x10, 0x47,
	0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x33, 0x0a, 0x09,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x39, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x6e,
	0x69, 0x75, 0x6e, 0x69, 0x75, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xce, 0x01, 0x0a,
	0x16, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x62, 0x65, 0x66, 0x6f, 0x72,
	0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18,
	0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6c, 0x6f,
	0x67, 0x69, 0x63, 0x2e, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x41, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x22, 0x29, 0x0a,
	0x15, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x6f, 0x62, 0x42, 0x61, 0x6e, 0x6b, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x62, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x62, 0x22, 0x42, 0x0a, 0x15, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x6f, 0x62, 0x42, 0x61, 0x6e, 0x6b, 0x65,
	0x72, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f,
	0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x62, 0x22, 0x2b, 0x0a, 0x10,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x42, 0x61, 0x6e, 0x6b, 0x65, 0x72, 0x53, 0x65, 0x61, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x13, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x42, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x72, 0x61, 0x74, 0x65, 0x22, 0x42, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x42, 0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x65,
	0x61, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x22, 0x4f, 0x0a, 0x15, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64,
	0x73, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61,
	0x6e, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x68, 0x61, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x73, 0x22, 0x4b, 0x0a, 0x13, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x34, 0x0a, 0x08, 0x6f, 0x75, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x6e, 0x69, 0x75, 0x6e, 0x69,
	0x75, 0x2e, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6f,
	0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x22, 0x64, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x08, 0x6f, 0x75, 0x74, 0x5f, 0x63, 0x61,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63,
	0x2e, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x2e, 0x4f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x07, 0x6f, 0x75, 0x74, 0x43, 0x61, 0x72, 0x64, 0x22, 0x93, 0x01, 0x0a,
	0x0f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x61, 0x6c, 0x6c, 0x79,
	0x12, 0x44, 0x0a, 0x09, 0x74, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x6e, 0x69, 0x75, 0x6e,
	0x69, 0x75, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x61, 0x6c,
	0x6c, 0x79, 0x2e, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x74, 0x61,
	0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x3a, 0x0a, 0x09, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x69, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x69,
	0x6e, 0x73, 0x2a, 0xa9, 0x01, 0x0a, 0x08, 0x42, 0x75, 0x6c, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0c, 0x0a, 0x08, 0x4e, 0x4f, 0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x57, 0x4f, 0x10, 0x02, 0x12,
	0x09, 0x0a, 0x05, 0x54, 0x48, 0x52, 0x45, 0x45, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x4f,
	0x55, 0x52, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x49, 0x56, 0x45, 0x10, 0x05, 0x12, 0x07,
	0x0a, 0x03, 0x53, 0x49, 0x58, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x45, 0x56, 0x45, 0x4e,
	0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x49, 0x47, 0x48, 0x54, 0x10, 0x08, 0x12, 0x08, 0x0a,
	0x04, 0x4e, 0x49, 0x4e, 0x45, 0x10, 0x09, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x55, 0x4c, 0x4c, 0x10,
	0x0a, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x4f, 0x55, 0x52, 0x42, 0x4f, 0x4d, 0x42, 0x10, 0x0b, 0x12,
	0x0e, 0x0a, 0x0a, 0x46, 0x49, 0x56, 0x45, 0x46, 0x4c, 0x4f, 0x57, 0x45, 0x52, 0x10, 0x0c, 0x12,
	0x0d, 0x0a, 0x09, 0x46, 0x49, 0x56, 0x45, 0x53, 0x4d, 0x41, 0x4c, 0x4c, 0x10, 0x0d, 0x2a, 0x8d,
	0x01, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a,
	0x04, 0x49, 0x44, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x55, 0x4e, 0x54,
	0x44, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x45, 0x47, 0x49, 0x4e, 0x10,
	0x02, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x41, 0x4e, 0x4b, 0x45, 0x52, 0x10, 0x03, 0x12, 0x11, 0x0a,
	0x0d, 0x42, 0x41, 0x4e, 0x4b, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x59, 0x10, 0x04,
	0x12, 0x07, 0x0a, 0x03, 0x42, 0x45, 0x54, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x45, 0x41,
	0x4c, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x53, 0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x48, 0x4f,
	0x57, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x53, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x41, 0x4c,
	0x4c, 0x59, 0x10, 0x08, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x56, 0x45, 0x52, 0x10, 0x09, 0x42, 0x19,
	0x5a, 0x08, 0x2e, 0x3b, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0xaa, 0x02, 0x0c, 0x67, 0x61, 0x6d,
	0x65, 0x73, 0x2e, 0x6e, 0x69, 0x75, 0x6e, 0x69, 0x75, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_niuniu_proto_rawDescOnce sync.Once
	file_niuniu_proto_rawDescData = file_niuniu_proto_rawDesc
)

func file_niuniu_proto_rawDescGZIP() []byte {
	file_niuniu_proto_rawDescOnce.Do(func() {
		file_niuniu_proto_rawDescData = protoimpl.X.CompressGZIP(file_niuniu_proto_rawDescData)
	})
	return file_niuniu_proto_rawDescData
}

var file_niuniu_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_niuniu_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_niuniu_proto_goTypes = []interface{}{
	(BullType)(0),                     // 0: logic.niuniu.BullType
	(GameStatus)(0),                   // 1: logic.niuniu.GameStatus
	(*OutCardInfo)(nil),               // 2: logic.niuniu.OutCardInfo
	(*PlayerInfo)(nil),                // 3: logic.niuniu.PlayerInfo
	(*GameInfo)(nil),                  // 4: logic.niuniu.GameInfo
	(*GameInfoRequest)(nil),           // 5: logic.niuniu.GameInfoRequest
	(*GameInfoResponse)(nil),          // 6: logic.niuniu.GameInfoResponse
	(*NotifyGameStatusChange)(nil),    // 7: logic.niuniu.NotifyGameStatusChange
	(*PlayerRobBankerReport)(nil),     // 8: logic.niuniu.PlayerRobBankerReport
	(*NotifyPlayerRobBanker)(nil),     // 9: logic.niuniu.NotifyPlayerRobBanker
	(*NotifyBankerSeat)(nil),          // 10: logic.niuniu.NotifyBankerSeat
	(*PlayerBetRateReport)(nil),       // 11: logic.niuniu.PlayerBetRateReport
	(*NotifyPlayerBetRate)(nil),       // 12: logic.niuniu.NotifyPlayerBetRate
	(*NotifyPlayerHandCards)(nil),     // 13: logic.niuniu.NotifyPlayerHandCards
	(*PlayerOutCardReport)(nil),       // 14: logic.niuniu.PlayerOutCardReport
	(*NotifyPlayerOutCard)(nil),       // 15: logic.niuniu.NotifyPlayerOutCard
	(*NotifyGameTally)(nil),           // 16: logic.niuniu.NotifyGameTally
	(*NotifyGameTally_TallyInfo)(nil), // 17: logic.niuniu.NotifyGameTally.TallyInfo
}
var file_niuniu_proto_depIdxs = []int32{
	0,  // 0: logic.niuniu.OutCardInfo.type:type_name -> logic.niuniu.BullType
	1,  // 1: logic.niuniu.PlayerInfo.status:type_name -> logic.niuniu.GameStatus
	2,  // 2: logic.niuniu.PlayerInfo.out_card:type_name -> logic.niuniu.OutCardInfo
	1,  // 3: logic.niuniu.GameInfo.status:type_name -> logic.niuniu.GameStatus
	4,  // 4: logic.niuniu.GameInfoResponse.game_info:type_name -> logic.niuniu.GameInfo
	3,  // 5: logic.niuniu.GameInfoResponse.player_info:type_name -> logic.niuniu.PlayerInfo
	1,  // 6: logic.niuniu.NotifyGameStatusChange.before_status:type_name -> logic.niuniu.GameStatus
	1,  // 7: logic.niuniu.NotifyGameStatusChange.curr_status:type_name -> logic.niuniu.GameStatus
	2,  // 8: logic.niuniu.PlayerOutCardReport.out_card:type_name -> logic.niuniu.OutCardInfo
	2,  // 9: logic.niuniu.NotifyPlayerOutCard.out_card:type_name -> logic.niuniu.OutCardInfo
	17, // 10: logic.niuniu.NotifyGameTally.tall_info:type_name -> logic.niuniu.NotifyGameTally.TallyInfo
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_niuniu_proto_init() }
func file_niuniu_proto_init() {
	if File_niuniu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_niuniu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutCardInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_niuniu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_niuniu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_niuniu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_niuniu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_niuniu_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyGameStatusChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_niuniu_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerRobBankerReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_niuniu_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyPlayerRobBanker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_niuniu_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyBankerSeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_niuniu_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerBetRateReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_niuniu_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyPlayerBetRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_niuniu_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyPlayerHandCards); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_niuniu_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerOutCardReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_niuniu_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyPlayerOutCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_niuniu_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyGameTally); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_niuniu_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyGameTally_TallyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_niuniu_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_niuniu_proto_goTypes,
		DependencyIndexes: file_niuniu_proto_depIdxs,
		EnumInfos:         file_niuniu_proto_enumTypes,
		MessageInfos:      file_niuniu_proto_msgTypes,
	}.Build()
	File_niuniu_proto = out.File
	file_niuniu_proto_rawDesc = nil
	file_niuniu_proto_goTypes = nil
	file_niuniu_proto_depIdxs = nil
}
