// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.18.1
// source: msg/battle.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerRoleType int32

const (
	PlayerRoleType_Player PlayerRoleType = 0
	PlayerRoleType_Robot  PlayerRoleType = 1
)

// Enum value maps for PlayerRoleType.
var (
	PlayerRoleType_name = map[int32]string{
		0: "Player",
		1: "Robot",
	}
	PlayerRoleType_value = map[string]int32{
		"Player": 0,
		"Robot":  1,
	}
)

func (x PlayerRoleType) Enum() *PlayerRoleType {
	p := new(PlayerRoleType)
	*p = x
	return p
}

func (x PlayerRoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerRoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_battlefield_proto_enumTypes[0].Descriptor()
}

func (PlayerRoleType) Type() protoreflect.EnumType {
	return &file_msg_battlefield_proto_enumTypes[0]
}

func (x PlayerRoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerRoleType.Descriptor instead.
func (PlayerRoleType) EnumDescriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{0}
}

type BattleStatus int32

const (
	BattleStatus_Idle    BattleStatus = 0
	BattleStatus_Started BattleStatus = 100
	BattleStatus_Over    BattleStatus = 200
)

// Enum value maps for BattleStatus.
var (
	BattleStatus_name = map[int32]string{
		0:   "Idle",
		100: "Started",
		200: "Over",
	}
	BattleStatus_value = map[string]int32{
		"Idle":    0,
		"Started": 100,
		"Over":    200,
	}
)

func (x BattleStatus) Enum() *BattleStatus {
	p := new(BattleStatus)
	*p = x
	return p
}

func (x BattleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_battlefield_proto_enumTypes[1].Descriptor()
}

func (BattleStatus) Type() protoreflect.EnumType {
	return &file_msg_battlefield_proto_enumTypes[1]
}

func (x BattleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattleStatus.Descriptor instead.
func (BattleStatus) EnumDescriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{1}
}

type ReportBattleOver_State int32

const (
	ReportBattleOver_Finished  ReportBattleOver_State = 0 // 完成
	ReportBattleOver_Disbanded ReportBattleOver_State = 1 // 解散
	ReportBattleOver_Timeover  ReportBattleOver_State = 2 // 超时
)

// Enum value maps for ReportBattleOver_State.
var (
	ReportBattleOver_State_name = map[int32]string{
		0: "Finished",
		1: "Disbanded",
		2: "Timeover",
	}
	ReportBattleOver_State_value = map[string]int32{
		"Finished":  0,
		"Disbanded": 1,
		"Timeover":  2,
	}
)

func (x ReportBattleOver_State) Enum() *ReportBattleOver_State {
	p := new(ReportBattleOver_State)
	*p = x
	return p
}

func (x ReportBattleOver_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportBattleOver_State) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_battlefield_proto_enumTypes[2].Descriptor()
}

func (ReportBattleOver_State) Type() protoreflect.EnumType {
	return &file_msg_battlefield_proto_enumTypes[2]
}

func (x ReportBattleOver_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportBattleOver_State.Descriptor instead.
func (ReportBattleOver_State) EnumDescriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{8, 0}
}

type CallError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Errmsg string `protobuf:"bytes,2,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
}

func (x *CallError) Reset() {
	*x = CallError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallError) ProtoMessage() {}

func (x *CallError) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallError.ProtoReflect.Descriptor instead.
func (*CallError) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{0}
}

func (x *CallError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CallError) GetErrmsg() string {
	if x != nil {
		return x.Errmsg
	}
	return ""
}

type MsgHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seqid   uint32     `protobuf:"varint,1,opt,name=seqid,proto3" json:"seqid,omitempty"`
	MsgType uint32     `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	MsgName string     `protobuf:"bytes,3,opt,name=msg_name,json=msgName,proto3" json:"msg_name,omitempty"`
	Err     *CallError `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *MsgHeader) Reset() {
	*x = MsgHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgHeader) ProtoMessage() {}

func (x *MsgHeader) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgHeader.ProtoReflect.Descriptor instead.
func (*MsgHeader) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{1}
}

func (x *MsgHeader) GetSeqid() uint32 {
	if x != nil {
		return x.Seqid
	}
	return 0
}

func (x *MsgHeader) GetMsgType() uint32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *MsgHeader) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *MsgHeader) GetErr() *CallError {
	if x != nil {
		return x.Err
	}
	return nil
}

type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       uint32            `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	SeatId    uint32            `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Role      PlayerRoleType    `protobuf:"varint,3,opt,name=role,proto3,enum=battle.PlayerRoleType" json:"role,omitempty"`
	MainScore int64             `protobuf:"varint,4,opt,name=main_score,json=mainScore,proto3" json:"main_score,omitempty"`
	SubScores []int64           `protobuf:"varint,5,rep,packed,name=sub_scores,json=subScores,proto3" json:"sub_scores,omitempty"`
	Extra     map[string]string `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerInfo) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerInfo) GetSeatId() uint32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *PlayerInfo) GetRole() PlayerRoleType {
	if x != nil {
		return x.Role
	}
	return PlayerRoleType_Player
}

func (x *PlayerInfo) GetMainScore() int64 {
	if x != nil {
		return x.MainScore
	}
	return 0
}

func (x *PlayerInfo) GetSubScores() []int64 {
	if x != nil {
		return x.SubScores
	}
	return nil
}

func (x *PlayerInfo) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type BattleConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxBattleTime uint32 `protobuf:"varint,1,opt,name=max_battle_time,json=maxBattleTime,proto3" json:"max_battle_time,omitempty"`
	BattleId      uint64 `protobuf:"varint,2,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
}

func (x *BattleConfig) Reset() {
	*x = BattleConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleConfig) ProtoMessage() {}

func (x *BattleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleConfig.ProtoReflect.Descriptor instead.
func (*BattleConfig) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{3}
}

func (x *BattleConfig) GetMaxBattleTime() uint32 {
	if x != nil {
		return x.MaxBattleTime
	}
	return 0
}

func (x *BattleConfig) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

type ReqStartBattle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleConf   *BattleConfig `protobuf:"bytes,1,opt,name=battle_conf,json=battleConf,proto3" json:"battle_conf,omitempty"`
	LogicName    string        `protobuf:"bytes,2,opt,name=logic_name,json=logicName,proto3" json:"logic_name,omitempty"`
	LogicVersion string        `protobuf:"bytes,3,opt,name=logic_version,json=logicVersion,proto3" json:"logic_version,omitempty"`
	LogicConf    []byte        `protobuf:"bytes,4,opt,name=logic_conf,json=logicConf,proto3" json:"logic_conf,omitempty"`
	PlayerInfos  []*PlayerInfo `protobuf:"bytes,5,rep,name=player_infos,json=playerInfos,proto3" json:"player_infos,omitempty"`
	CallbackUrl  string        `protobuf:"bytes,6,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
}

func (x *ReqStartBattle) Reset() {
	*x = ReqStartBattle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStartBattle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStartBattle) ProtoMessage() {}

func (x *ReqStartBattle) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStartBattle.ProtoReflect.Descriptor instead.
func (*ReqStartBattle) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{4}
}

func (x *ReqStartBattle) GetBattleConf() *BattleConfig {
	if x != nil {
		return x.BattleConf
	}
	return nil
}

func (x *ReqStartBattle) GetLogicName() string {
	if x != nil {
		return x.LogicName
	}
	return ""
}

func (x *ReqStartBattle) GetLogicVersion() string {
	if x != nil {
		return x.LogicVersion
	}
	return ""
}

func (x *ReqStartBattle) GetLogicConf() []byte {
	if x != nil {
		return x.LogicConf
	}
	return nil
}

func (x *ReqStartBattle) GetPlayerInfos() []*PlayerInfo {
	if x != nil {
		return x.PlayerInfos
	}
	return nil
}

func (x *ReqStartBattle) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type RespStartBattle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId uint64 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
}

func (x *RespStartBattle) Reset() {
	*x = RespStartBattle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespStartBattle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespStartBattle) ProtoMessage() {}

func (x *RespStartBattle) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespStartBattle.ProtoReflect.Descriptor instead.
func (*RespStartBattle) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{5}
}

func (x *RespStartBattle) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

type ReqStopBattle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId uint64 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
}

func (x *ReqStopBattle) Reset() {
	*x = ReqStopBattle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStopBattle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStopBattle) ProtoMessage() {}

func (x *ReqStopBattle) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStopBattle.ProtoReflect.Descriptor instead.
func (*ReqStopBattle) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{6}
}

func (x *ReqStopBattle) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

type RespStopBattle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RespStopBattle) Reset() {
	*x = RespStopBattle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespStopBattle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespStopBattle) ProtoMessage() {}

func (x *RespStopBattle) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespStopBattle.ProtoReflect.Descriptor instead.
func (*RespStopBattle) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{7}
}

type ReportBattleOver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State ReportBattleOver_State                  `protobuf:"varint,1,opt,name=state,proto3,enum=battle.ReportBattleOver_State" json:"state,omitempty"`
	Tally map[int32]*ReportBattleOver_BattleScore `protobuf:"bytes,2,rep,name=tally,proto3" json:"tally,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ReportBattleOver) Reset() {
	*x = ReportBattleOver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportBattleOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportBattleOver) ProtoMessage() {}

func (x *ReportBattleOver) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportBattleOver.ProtoReflect.Descriptor instead.
func (*ReportBattleOver) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{8}
}

func (x *ReportBattleOver) GetState() ReportBattleOver_State {
	if x != nil {
		return x.State
	}
	return ReportBattleOver_Finished
}

func (x *ReportBattleOver) GetTally() map[int32]*ReportBattleOver_BattleScore {
	if x != nil {
		return x.Tally
	}
	return nil
}

type EventBattleStatusChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId     uint64 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	StatusBefore int32  `protobuf:"varint,2,opt,name=status_before,json=statusBefore,proto3" json:"status_before,omitempty"`
	StatusNow    int32  `protobuf:"varint,3,opt,name=status_now,json=statusNow,proto3" json:"status_now,omitempty"`
}

func (x *EventBattleStatusChange) Reset() {
	*x = EventBattleStatusChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventBattleStatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBattleStatusChange) ProtoMessage() {}

func (x *EventBattleStatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBattleStatusChange.ProtoReflect.Descriptor instead.
func (*EventBattleStatusChange) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{9}
}

func (x *EventBattleStatusChange) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *EventBattleStatusChange) GetStatusBefore() int32 {
	if x != nil {
		return x.StatusBefore
	}
	return 0
}

func (x *EventBattleStatusChange) GetStatusNow() int32 {
	if x != nil {
		return x.StatusNow
	}
	return 0
}

type EventBattleStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EventBattleStart) Reset() {
	*x = EventBattleStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventBattleStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBattleStart) ProtoMessage() {}

func (x *EventBattleStart) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBattleStart.ProtoReflect.Descriptor instead.
func (*EventBattleStart) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{10}
}

type EventBattleOver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EventBattleOver) Reset() {
	*x = EventBattleOver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventBattleOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBattleOver) ProtoMessage() {}

func (x *EventBattleOver) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBattleOver.ProtoReflect.Descriptor instead.
func (*EventBattleOver) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{11}
}

type ReqJoinBattle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId   uint64 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	ReadyState int32  `protobuf:"varint,2,opt,name=ready_state,json=readyState,proto3" json:"ready_state,omitempty"`
}

func (x *ReqJoinBattle) Reset() {
	*x = ReqJoinBattle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqJoinBattle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqJoinBattle) ProtoMessage() {}

func (x *ReqJoinBattle) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqJoinBattle.ProtoReflect.Descriptor instead.
func (*ReqJoinBattle) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{12}
}

func (x *ReqJoinBattle) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *ReqJoinBattle) GetReadyState() int32 {
	if x != nil {
		return x.ReadyState
	}
	return 0
}

type RespJoinBattle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReadyInfo []*RespJoinBattle_ReadyInfo `protobuf:"bytes,1,rep,name=ready_info,json=readyInfo,proto3" json:"ready_info,omitempty"`
}

func (x *RespJoinBattle) Reset() {
	*x = RespJoinBattle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespJoinBattle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespJoinBattle) ProtoMessage() {}

func (x *RespJoinBattle) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespJoinBattle.ProtoReflect.Descriptor instead.
func (*RespJoinBattle) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{13}
}

func (x *RespJoinBattle) GetReadyInfo() []*RespJoinBattle_ReadyInfo {
	if x != nil {
		return x.ReadyInfo
	}
	return nil
}

type ReqQuitBattle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId uint64 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
}

func (x *ReqQuitBattle) Reset() {
	*x = ReqQuitBattle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqQuitBattle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqQuitBattle) ProtoMessage() {}

func (x *ReqQuitBattle) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqQuitBattle.ProtoReflect.Descriptor instead.
func (*ReqQuitBattle) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{14}
}

func (x *ReqQuitBattle) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

type RespQuitBattle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId uint64 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
}

func (x *RespQuitBattle) Reset() {
	*x = RespQuitBattle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespQuitBattle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespQuitBattle) ProtoMessage() {}

func (x *RespQuitBattle) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespQuitBattle.ProtoReflect.Descriptor instead.
func (*RespQuitBattle) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{15}
}

func (x *RespQuitBattle) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

type BattleMessageWrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleId uint64 `protobuf:"varint,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Head     []byte `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
	Body     []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *BattleMessageWrap) Reset() {
	*x = BattleMessageWrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleMessageWrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleMessageWrap) ProtoMessage() {}

func (x *BattleMessageWrap) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleMessageWrap.ProtoReflect.Descriptor instead.
func (*BattleMessageWrap) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{16}
}

func (x *BattleMessageWrap) GetBattleId() uint64 {
	if x != nil {
		return x.BattleId
	}
	return 0
}

func (x *BattleMessageWrap) GetHead() []byte {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *BattleMessageWrap) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type NotifyPlayerStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId   uint32 `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	IsOnline bool   `protobuf:"varint,2,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
}

func (x *NotifyPlayerStatus) Reset() {
	*x = NotifyPlayerStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyPlayerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPlayerStatus) ProtoMessage() {}

func (x *NotifyPlayerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPlayerStatus.ProtoReflect.Descriptor instead.
func (*NotifyPlayerStatus) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{17}
}

func (x *NotifyPlayerStatus) GetSeatId() uint32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *NotifyPlayerStatus) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

type NotifyBattleStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status BattleStatus `protobuf:"varint,1,opt,name=status,proto3,enum=battle.BattleStatus" json:"status,omitempty"`
}

func (x *NotifyBattleStatus) Reset() {
	*x = NotifyBattleStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyBattleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBattleStatus) ProtoMessage() {}

func (x *NotifyBattleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBattleStatus.ProtoReflect.Descriptor instead.
func (*NotifyBattleStatus) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{18}
}

func (x *NotifyBattleStatus) GetStatus() BattleStatus {
	if x != nil {
		return x.Status
	}
	return BattleStatus_Idle
}

type BattleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrStatus BattleStatus `protobuf:"varint,1,opt,name=curr_status,json=currStatus,proto3,enum=battle.BattleStatus" json:"curr_status,omitempty"`
}

func (x *BattleInfo) Reset() {
	*x = BattleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleInfo) ProtoMessage() {}

func (x *BattleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleInfo.ProtoReflect.Descriptor instead.
func (*BattleInfo) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{19}
}

func (x *BattleInfo) GetCurrStatus() BattleStatus {
	if x != nil {
		return x.CurrStatus
	}
	return BattleStatus_Idle
}

type ReqBattleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqBattleInfo) Reset() {
	*x = ReqBattleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqBattleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqBattleInfo) ProtoMessage() {}

func (x *ReqBattleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqBattleInfo.ProtoReflect.Descriptor instead.
func (*ReqBattleInfo) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{20}
}

type RespBattlInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleInfo  *BattleInfo   `protobuf:"bytes,1,opt,name=battle_info,json=battleInfo,proto3" json:"battle_info,omitempty"`
	PlayerInfos []*PlayerInfo `protobuf:"bytes,2,rep,name=player_infos,json=playerInfos,proto3" json:"player_infos,omitempty"`
}

func (x *RespBattlInfo) Reset() {
	*x = RespBattlInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespBattlInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespBattlInfo) ProtoMessage() {}

func (x *RespBattlInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespBattlInfo.ProtoReflect.Descriptor instead.
func (*RespBattlInfo) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{21}
}

func (x *RespBattlInfo) GetBattleInfo() *BattleInfo {
	if x != nil {
		return x.BattleInfo
	}
	return nil
}

func (x *RespBattlInfo) GetPlayerInfos() []*PlayerInfo {
	if x != nil {
		return x.PlayerInfos
	}
	return nil
}

type MsgToClientWrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head []byte `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *MsgToClientWrap) Reset() {
	*x = MsgToClientWrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgToClientWrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgToClientWrap) ProtoMessage() {}

func (x *MsgToClientWrap) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgToClientWrap.ProtoReflect.Descriptor instead.
func (*MsgToClientWrap) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{22}
}

func (x *MsgToClientWrap) GetHead() []byte {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *MsgToClientWrap) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type MsgToLogicWrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head []byte `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *MsgToLogicWrap) Reset() {
	*x = MsgToLogicWrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgToLogicWrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgToLogicWrap) ProtoMessage() {}

func (x *MsgToLogicWrap) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgToLogicWrap.ProtoReflect.Descriptor instead.
func (*MsgToLogicWrap) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{23}
}

func (x *MsgToLogicWrap) GetHead() []byte {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *MsgToLogicWrap) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ReportBattleOver_BattleScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score int64             `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Extra map[string]string `protobuf:"bytes,2,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ReportBattleOver_BattleScore) Reset() {
	*x = ReportBattleOver_BattleScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportBattleOver_BattleScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportBattleOver_BattleScore) ProtoMessage() {}

func (x *ReportBattleOver_BattleScore) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportBattleOver_BattleScore.ProtoReflect.Descriptor instead.
func (*ReportBattleOver_BattleScore) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ReportBattleOver_BattleScore) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ReportBattleOver_BattleScore) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type RespJoinBattle_ReadyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatId     uint32 `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Uid        uint32 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	ReadyState int32  `protobuf:"varint,3,opt,name=ready_state,json=readyState,proto3" json:"ready_state,omitempty"`
}

func (x *RespJoinBattle_ReadyInfo) Reset() {
	*x = RespJoinBattle_ReadyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_battlefield_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespJoinBattle_ReadyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespJoinBattle_ReadyInfo) ProtoMessage() {}

func (x *RespJoinBattle_ReadyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_battlefield_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespJoinBattle_ReadyInfo.ProtoReflect.Descriptor instead.
func (*RespJoinBattle_ReadyInfo) Descriptor() ([]byte, []int) {
	return file_msg_battlefield_proto_rawDescGZIP(), []int{13, 0}
}

func (x *RespJoinBattle_ReadyInfo) GetSeatId() uint32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *RespJoinBattle_ReadyInfo) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RespJoinBattle_ReadyInfo) GetReadyState() int32 {
	if x != nil {
		return x.ReadyState
	}
	return 0
}

var File_msg_battlefield_proto protoreflect.FileDescriptor

var file_msg_battlefield_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x73, 0x67, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x22, 0x37, 0x0a, 0x09, 0x43, 0x61, 0x6c, 0x6c, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6d, 0x73, 0x67, 0x22, 0x81, 0x01,
	0x0a, 0x09, 0x4d, 0x73, 0x67, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x65, 0x71, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x65, 0x71, 0x69,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x6d, 0x73, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x73, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x65, 0x72,
	0x72, 0x22, 0x9a, 0x02, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x6f,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x6d, 0x61, 0x69, 0x6e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x75, 0x62, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x75, 0x62, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x05, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65,
	0x78, 0x74, 0x72, 0x61, 0x1a, 0x38, 0x0a, 0x0a, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x53,
	0x0a, 0x0c, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x26,
	0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6d, 0x61, 0x78, 0x42, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x49, 0x64, 0x22, 0x8e, 0x02, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0a, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x3a, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x55, 0x72, 0x6c, 0x22, 0x2e, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x53, 0x74, 0x6f, 0x70, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x53, 0x74, 0x6f, 0x70, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x22, 0xd2, 0x03, 0x0a, 0x10, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x3e, 0x0a, 0x05, 0x74, 0x61, 0x6c, 0x6c, 0x79, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4f, 0x76,
	0x65, 0x72, 0x2e, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x74,
	0x61, 0x6c, 0x6c, 0x79, 0x1a, 0xa9, 0x01, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x4a, 0x0a, 0x05, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x05, 0x65, 0x78, 0x74, 0x72, 0x61, 0x1a, 0x38, 0x0a, 0x0a, 0x45, 0x78, 0x74, 0x72, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x1a, 0x63, 0x0a, 0x0a, 0x54, 0x61, 0x6c, 0x6c, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x3f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x29, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x2e, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x32, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0c,
	0x0a, 0x08, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x44, 0x69, 0x73, 0x62, 0x61, 0x6e, 0x64, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x54,
	0x69, 0x6d, 0x65, 0x6f, 0x76, 0x65, 0x72, 0x10, 0x02, 0x22, 0x7a, 0x0a, 0x17, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x62, 0x65, 0x66, 0x6f,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x5f, 0x6e, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x4e, 0x6f, 0x77, 0x22, 0x12, 0x0a, 0x10, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x22, 0x4d, 0x0a, 0x0d,
	0x52, 0x65, 0x71, 0x4a, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65,
	0x61, 0x64, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x72, 0x65, 0x61, 0x64, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0xaf, 0x01, 0x0a, 0x0e,
	0x52, 0x65, 0x73, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x44,
	0x0a, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x72, 0x65, 0x61, 0x64, 0x79,
	0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x57, 0x0a, 0x09, 0x52, 0x65, 0x61, 0x64, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x73, 0x65, 0x61, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x72, 0x65, 0x61, 0x64, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x2c, 0x0a,
	0x0d, 0x52, 0x65, 0x71, 0x51, 0x75, 0x69, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x0e, 0x52,
	0x65, 0x73, 0x70, 0x51, 0x75, 0x69, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x58, 0x0a, 0x11, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x57, 0x72, 0x61, 0x70, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x65, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x22, 0x4a, 0x0a, 0x12, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65,
	0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x65, 0x61,
	0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x22, 0x47, 0x0a, 0x12, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x48, 0x0a, 0x0a, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3a, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x38, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x3a, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x39, 0x0a, 0x0f,
	0x4d, 0x73, 0x67, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x57, 0x72, 0x61, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68,
	0x65, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x38, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x54, 0x6f,
	0x4c, 0x6f, 0x67, 0x69, 0x63, 0x57, 0x72, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x61,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x2a, 0x27, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x10, 0x00, 0x12,
	0x09, 0x0a, 0x05, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x10, 0x01, 0x2a, 0x30, 0x0a, 0x0c, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x64,
	0x6c, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x10,
	0x64, 0x12, 0x09, 0x0a, 0x04, 0x4f, 0x76, 0x65, 0x72, 0x10, 0xc8, 0x01, 0x32, 0xaf, 0x02, 0x0a,
	0x06, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x1a, 0x1c, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x70, 0x42, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x12, 0x1a, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e,
	0x52, 0x65, 0x71, 0x53, 0x74, 0x6f, 0x70, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x1a, 0x1b, 0x2e,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x53, 0x74, 0x6f, 0x70, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a,
	0x4a, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x62, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x4a, 0x6f, 0x69, 0x6e,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x1a, 0x1b, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0a, 0x51, 0x75, 0x69, 0x74, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x2e, 0x52, 0x65, 0x71, 0x51, 0x75, 0x69, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x1a,
	0x1b, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x51, 0x75, 0x69, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x22, 0x00, 0x42, 0x06,
	0x5a, 0x04, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_battlefield_proto_rawDescOnce sync.Once
	file_msg_battlefield_proto_rawDescData = file_msg_battlefield_proto_rawDesc
)

func file_msg_battlefield_proto_rawDescGZIP() []byte {
	file_msg_battlefield_proto_rawDescOnce.Do(func() {
		file_msg_battlefield_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_battlefield_proto_rawDescData)
	})
	return file_msg_battlefield_proto_rawDescData
}

var file_msg_battlefield_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_msg_battlefield_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_msg_battlefield_proto_goTypes = []interface{}{
	(PlayerRoleType)(0),                  // 0: battle.PlayerRoleType
	(BattleStatus)(0),                    // 1: battle.BattleStatus
	(ReportBattleOver_State)(0),          // 2: battle.ReportBattleOver.State
	(*CallError)(nil),                    // 3: battle.CallError
	(*MsgHeader)(nil),                    // 4: battle.MsgHeader
	(*PlayerInfo)(nil),                   // 5: battle.PlayerInfo
	(*BattleConfig)(nil),                 // 6: battle.BattleConfig
	(*ReqStartBattle)(nil),               // 7: battle.ReqStartBattle
	(*RespStartBattle)(nil),              // 8: battle.RespStartBattle
	(*ReqStopBattle)(nil),                // 9: battle.ReqStopBattle
	(*RespStopBattle)(nil),               // 10: battle.RespStopBattle
	(*ReportBattleOver)(nil),             // 11: battle.ReportBattleOver
	(*EventBattleStatusChange)(nil),      // 12: battle.EventBattleStatusChange
	(*EventBattleStart)(nil),             // 13: battle.EventBattleStart
	(*EventBattleOver)(nil),              // 14: battle.EventBattleOver
	(*ReqJoinBattle)(nil),                // 15: battle.ReqJoinBattle
	(*RespJoinBattle)(nil),               // 16: battle.RespJoinBattle
	(*ReqQuitBattle)(nil),                // 17: battle.ReqQuitBattle
	(*RespQuitBattle)(nil),               // 18: battle.RespQuitBattle
	(*BattleMessageWrap)(nil),            // 19: battle.BattleMessageWrap
	(*NotifyPlayerStatus)(nil),           // 20: battle.NotifyPlayerStatus
	(*NotifyBattleStatus)(nil),           // 21: battle.NotifyBattleStatus
	(*BattleInfo)(nil),                   // 22: battle.BattleInfo
	(*ReqBattleInfo)(nil),                // 23: battle.ReqBattleInfo
	(*RespBattlInfo)(nil),                // 24: battle.RespBattlInfo
	(*MsgToClientWrap)(nil),              // 25: battle.MsgToClientWrap
	(*MsgToLogicWrap)(nil),               // 26: battle.MsgToLogicWrap
	nil,                                  // 27: battle.PlayerInfo.ExtraEntry
	(*ReportBattleOver_BattleScore)(nil), // 28: battle.ReportBattleOver.BattleScore
	nil,                                  // 29: battle.ReportBattleOver.TallyEntry
	nil,                                  // 30: battle.ReportBattleOver.BattleScore.ExtraEntry
	(*RespJoinBattle_ReadyInfo)(nil),     // 31: battle.RespJoinBattle.ReadyInfo
}
var file_msg_battlefield_proto_depIdxs = []int32{
	3,  // 0: battle.MsgHeader.err:type_name -> battle.CallError
	0,  // 1: battle.PlayerInfo.role:type_name -> battle.PlayerRoleType
	27, // 2: battle.PlayerInfo.extra:type_name -> battle.PlayerInfo.ExtraEntry
	6,  // 3: battle.ReqStartBattle.battle_conf:type_name -> battle.BattleConfig
	5,  // 4: battle.ReqStartBattle.player_infos:type_name -> battle.PlayerInfo
	2,  // 5: battle.ReportBattleOver.state:type_name -> battle.ReportBattleOver.State
	29, // 6: battle.ReportBattleOver.tally:type_name -> battle.ReportBattleOver.TallyEntry
	31, // 7: battle.RespJoinBattle.ready_info:type_name -> battle.RespJoinBattle.ReadyInfo
	1,  // 8: battle.NotifyBattleStatus.status:type_name -> battle.BattleStatus
	1,  // 9: battle.BattleInfo.curr_status:type_name -> battle.BattleStatus
	22, // 10: battle.RespBattlInfo.battle_info:type_name -> battle.BattleInfo
	5,  // 11: battle.RespBattlInfo.player_infos:type_name -> battle.PlayerInfo
	30, // 12: battle.ReportBattleOver.BattleScore.extra:type_name -> battle.ReportBattleOver.BattleScore.ExtraEntry
	28, // 13: battle.ReportBattleOver.TallyEntry.value:type_name -> battle.ReportBattleOver.BattleScore
	7,  // 14: battle.Battle.StartBattle:input_type -> battle.ReqStartBattle
	9,  // 15: battle.Battle.StopBattle:input_type -> battle.ReqStopBattle
	15, // 16: battle.Battle.JoinBattle:input_type -> battle.ReqJoinBattle
	17, // 17: battle.Battle.QuitBattle:input_type -> battle.ReqQuitBattle
	8,  // 18: battle.Battle.StartBattle:output_type -> battle.RespStartBattle
	10, // 19: battle.Battle.StopBattle:output_type -> battle.RespStopBattle
	16, // 20: battle.Battle.JoinBattle:output_type -> battle.RespJoinBattle
	18, // 21: battle.Battle.QuitBattle:output_type -> battle.RespQuitBattle
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_msg_battlefield_proto_init() }
func file_msg_battlefield_proto_init() {
	if File_msg_battlefield_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_battlefield_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStartBattle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespStartBattle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStopBattle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespStopBattle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportBattleOver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventBattleStatusChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventBattleStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventBattleOver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqJoinBattle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespJoinBattle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqQuitBattle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespQuitBattle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleMessageWrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyPlayerStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyBattleStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqBattleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespBattlInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgToClientWrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgToLogicWrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportBattleOver_BattleScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_battlefield_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespJoinBattle_ReadyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_battlefield_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msg_battlefield_proto_goTypes,
		DependencyIndexes: file_msg_battlefield_proto_depIdxs,
		EnumInfos:         file_msg_battlefield_proto_enumTypes,
		MessageInfos:      file_msg_battlefield_proto_msgTypes,
	}.Build()
	File_msg_battlefield_proto = out.File
	file_msg_battlefield_proto_rawDesc = nil
	file_msg_battlefield_proto_goTypes = nil
	file_msg_battlefield_proto_depIdxs = nil
}
